#!/bin/bash

rm /root/ceremonyclient
rm /root/go/bin/node
rm /lib/systemd/system/ceremonyclient.service

# Clone the repository and run the application
cd $HOME
git clone https://github.com/QuilibriumNetwork/ceremonyclient.git
cd ceremonyclient/node

# Run the Go program in the background
GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... &

# Wait for a few seconds before rebooting
sleep 300

# Reboot the system
echo "Rebooting..."
sudo reboot
