#!/bin/bash

# Remove existing systemd service file
sudo rm -f /lib/systemd/system/ceremonyclient.service

# Clone the repository and run the application
cd $HOME || exit
git clone https://github.com/QuilibriumNetwork/ceremonyclient.git
cd ceremonyclient/node || exit

# Start the Go program in the background
GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... &
